Desktop version
Ceemos96/Portfolio-setup-and-mobile-version-skeleton pull request #5
Opened 2022-04-28 10:16 UTC by Ceemos96

### Desktop Version Project
### in this project i : 
- Added Svg files for the Desktop version background
- Created a media query for screens with a min width of 768px
- Styled the menu items for big screens
- Used css grid to style the layout of the projects and technologies section
- Styled the contact section using css grip

2022-04-28 12:06 UTC, codepantha requested changes
Hi @Ceemos96 👋, 

## STATUS: REQUESTED CHANGES ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/km2mais9qzYI/giphy.gif"/>

### To Highlight 🎯 ⭐ 
- Descriptive PR ✔️ 
- Meaningful commit messages ✔️ 
- Linter checks ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 12:06 UTC, codepantha commented on index.html
> +            </div>
- [ ] On screens `768px` wide and above, this headline section is aligned to the right instead of being centered as shown in the Figma design. Please fix it 🙏 
- [ ] Please adjust the` margin-bottom` to look like the design
### Your Design
![image](https://user-images.githubusercontent.com/46839548/165741888-fbf491a9-9491-436c-8b61-98d86671c4f7.png)
### Figma Design
![image](https://user-images.githubusercontent.com/46839548/165742011-a1ba2f16-2ca7-4d8d-95cf-c6744b77c03f.png)

2022-04-28 12:06 UTC, codepantha commented on index.html
> +                  <a href="#" class="nav-link">Portfolio</a>
- [ ] Your navbar is aligned to the left instead of being centered in accordance with the Figma design on screen sizes `768px` and above 👇 . Please fix it.
### Your Design
![image](https://user-images.githubusercontent.com/46839548/165742905-d4c0b90a-7d47-4691-b37c-91ef194f703a.png)
### Figma Design
![image](https://user-images.githubusercontent.com/46839548/165743298-518e8049-fb56-40e1-a3fb-8dd98aff1024.png)

2022-04-28 12:06 UTC, codepantha commented on index.html
> +                <ul class="lang-list">
- [ ] Please center the content of the projects section and remove the horizontal scrolling. This will improve your UI  👍 
### Your Design
![image](https://user-images.githubusercontent.com/46839548/165745511-99b11c5f-b960-4e38-bf3b-501124f65e53.png)

### Figma Design
![image](https://user-images.githubusercontent.com/46839548/165745955-0994cf61-504d-4b94-a4ca-ed4292ee6dcc.png)

2022-04-28 12:06 UTC, codepantha commented on index.html
> +          />
- [ ] Please adjust your about section to be centered on screen sizes from `768px` and above just like the Figma design
### Your Design
![image](https://user-images.githubusercontent.com/46839548/165746663-a1dfde63-4aa6-4808-8263-667f14a174df.png)

### Figma Design
![image](https://user-images.githubusercontent.com/46839548/165746788-9378ab99-0dc1-4aba-95c7-0b43318e5f87.png)

2022-04-28 12:06 UTC, codepantha commented on index.html
> +              alt="contact-background"
- [ ] Please adjust your contact section to be centered just like the Figma design on screen sizes from `768px` and above 👇 
### Your Design
![image](https://user-images.githubusercontent.com/46839548/165747508-11033bed-ca7a-446c-b1b3-896d3e8a6d43.png)
### Figma Design
![image](https://user-images.githubusercontent.com/46839548/165747327-32448d2e-a583-43c2-93a1-f46853b608d1.png)

2022-04-28 13:53 UTC, merged

2022-04-29 06:28 UTC, Ceemos96 commented on index.html
> +            </div>
Gooday 🌞 , 

A collaborator on my project merged the pull request by mistake before i got to apply all the suggested fixes.
Here's a link to the new PR i created: https://github.com/Ceemos96/Portfolio-setup-and-mobile-version-skeleton/pull/7

cheers 🥂